"""Distilled params for ablation variant v01_mm_only."""
from __future__ import annotations

POSITION_LIMIT = 10
PEBBLES = ["PEBBLES_L","PEBBLES_M","PEBBLES_S","PEBBLES_XL","PEBBLES_XS"]
SNACKPACKS = ["SNACKPACK_CHOCOLATE","SNACKPACK_PISTACHIO","SNACKPACK_RASPBERRY","SNACKPACK_STRAWBERRY","SNACKPACK_VANILLA"]
MICROCHIPS = ["MICROCHIP_CIRCLE","MICROCHIP_OVAL","MICROCHIP_RECTANGLE","MICROCHIP_SQUARE","MICROCHIP_TRIANGLE"]
SLEEP_PODS = ["SLEEP_POD_COTTON","SLEEP_POD_LAMB_WOOL","SLEEP_POD_NYLON","SLEEP_POD_POLYESTER","SLEEP_POD_SUEDE"]
ROBOTS = ["ROBOT_DISHES","ROBOT_IRONING","ROBOT_LAUNDRY","ROBOT_MOPPING","ROBOT_VACUUMING"]
GALAXY = ["GALAXY_SOUNDS_BLACK_HOLES","GALAXY_SOUNDS_DARK_MATTER","GALAXY_SOUNDS_PLANETARY_RINGS","GALAXY_SOUNDS_SOLAR_FLAMES","GALAXY_SOUNDS_SOLAR_WINDS"]
OXYGEN = ["OXYGEN_SHAKE_CHOCOLATE","OXYGEN_SHAKE_EVENING_BREATH","OXYGEN_SHAKE_GARLIC","OXYGEN_SHAKE_MINT","OXYGEN_SHAKE_MORNING_BREATH"]
PANELS = ["PANEL_1X2","PANEL_1X4","PANEL_2X2","PANEL_2X4","PANEL_4X4"]
TRANSLATORS = ["TRANSLATOR_ASTRO_BLACK","TRANSLATOR_ECLIPSE_CHARCOAL","TRANSLATOR_GRAPHITE_MIST","TRANSLATOR_SPACE_GRAY","TRANSLATOR_VOID_BLUE"]
UV_VISORS = ["UV_VISOR_AMBER","UV_VISOR_MAGENTA","UV_VISOR_ORANGE","UV_VISOR_RED","UV_VISOR_YELLOW"]
ALL_PRODUCTS = PEBBLES + SNACKPACKS + MICROCHIPS + SLEEP_PODS + ROBOTS + GALAXY + OXYGEN + PANELS + TRANSLATORS + UV_VISORS

PROD_CAP = {}
PEBBLES_SUM_TARGET = 50000.0
SNACKPACK_SUM_TARGET = 50221.0
PEBBLES_SKEW_DIVISOR = 5.0
SNACKPACK_SKEW_DIVISOR = 5.0
PEBBLES_SKEW_CLIP = 3.0
SNACKPACK_SKEW_CLIP = 5.0
PEBBLES_BIG_SKEW = 1.8
SNACKPACK_BIG_SKEW = 3.5

COINT_PAIRS = []
CROSS_GROUP_PAIRS = []

PAIR_TILT_DIVISOR = 8.0
PAIR_TILT_CLIP = 3.0
INV_SKEW_BETA = 0.0
QUOTE_BASE_SIZE_CAP = 8
QUOTE_AGGRESSIVE_SIZE = 2

PEBBLES_L_CAP = None
ENABLE_AR1_EVB_SKEW = False
EVB_AR1_ALPHA = 1.5

DISABLE_PEBBLES = True
DISABLE_SNACKPACK = True
